// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the full set of user-configurable behaviour.
 * 
 * Durations are split into the unit the UI naturally edits in (minutes for the
 * long ones, seconds for the short break) and reconciled to time.Duration by
 * the break engine.
 */
export interface Settings {
    /**
     * FocusDurationMin is how long a focus period lasts before a break is due.
     */
    "focusDurationMin": number;

    /**
     * ShortBreakDurationSec is the length of a regular (short) break.
     */
    "shortBreakDurationSec": number;

    /**
     * LongBreakDurationMin is the length of an occasional longer break.
     */
    "longBreakDurationMin": number;

    /**
     * LongBreakInterval is how many short breaks happen before a long break.
     */
    "longBreakInterval": number;

    /**
     * PreBreakWarningSec is the heads-up shown before a break starts.
     */
    "preBreakWarningSec": number;

    /**
     * IdleThresholdMin: after this many minutes of inactivity the focus timer
     * is treated as paused and resets when activity resumes.
     */
    "idleThresholdMin": number;

    /**
     * EnableLongBreaks toggles the occasional long-break cycle.
     */
    "enableLongBreaks": boolean;

    /**
     * SoundEnabled toggles the break-end chime and pre-break tick.
     */
    "soundEnabled": boolean;

    /**
     * AutoStart launches the focus timer automatically when the app starts
     * (after onboarding). When false, the user starts it manually from the tray.
     */
    "autoStart": boolean;

    /**
     * Onboarded records whether the user has completed the first-run setup.
     * Until it is true the engine does not run a countdown, so the app opens
     * to a setup screen instead of immediately counting down.
     */
    "onboarded": boolean;

    /**
     * Language is the UI locale, "zh-CN" or "en" (empty = follow system).
     */
    "language": string;

    /**
     * Global keyboard shortcuts (Wails accelerator syntax, e.g. "Cmd+Shift+B").
     */
    "shortcutStartBreak": string;
    "shortcutSkipBreak": string;
    "shortcutPostponeBreak": string;
    "shortcutPreferences": string;
}
