// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DayStats 是单日的统计聚合。
 */
export interface DayStats {
    /**
     * FocusSec 是当日累计专注秒数。
     */
    "focusSec": number;

    /**
     * BreakSec 是当日累计休息秒数（短休息 + 长休息）。
     */
    "breakSec": number;

    /**
     * ShortBreaks 是当日完成的短休息次数。
     */
    "shortBreaks": number;

    /**
     * LongBreaks 是当日完成的长休息次数。
     */
    "longBreaks": number;
}
