// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as breakengine$0 from "../../../../../blink/internal/breakengine/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "blink:nav": string;
            "blink:tick": breakengine$0.State;
        }
    }
}
