// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Phase 是引擎当前所处的高层状态。它以字符串形式发送给前端，
 * 这样 UI 无需解析数字就能切换视图。
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PhaseFocusing：工作周期正在倒计时，等待下一次休息。
     */
    PhaseFocusing = "focusing",

    /**
     * PhasePreBreak：休息开始前的提醒窗口。
     */
    PhasePreBreak = "prebreak",

    /**
     * PhaseShortBreak：常规短休息遮罩正在显示。
     */
    PhaseShortBreak = "shortbreak",

    /**
     * PhaseLongBreak：偶尔的较长休息遮罩正在显示。
     */
    PhaseLongBreak = "longbreak",

    /**
     * PhaseIdle：用户不活动时间超过空闲阈值；专注计时器被保持，
     * 活动恢复后重置。
     * 
     * 注意：没有 PhasePaused 常量。Pause() 通过设置实时布尔值 e.paused
     * 来冻结倒计时，不改变阶段，所以用户暂停时的阶段值就是调用 Pause
     * 时的阶段（通常是 PhaseFocusing）。前端读取 State 中发出的 `paused`
     * 布尔值来检测暂停，而不是阶段字符串。
     */
    PhaseIdle = "idle",
};

/**
 * State 是每次 tick 和阶段变更时发送给前端的状态快照。
 * 时长以整秒表示，方便 UI 格式化。
 */
export interface State {
    "phase": Phase;
    "remainingSec": number;
    "totalSec": number;
    "breaksUntilLong": number;
    "shortBreakCount": number;
    "idle": boolean;
    "paused": boolean;
}
