// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Phase is the high-level state the engine is currently in. It is emitted to
 * the frontend as a string so the UI can switch views without parsing numbers.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PhaseFocusing: a work period is counting down toward the next break.
     */
    PhaseFocusing = "focusing",

    /**
     * PhasePreBreak: the heads-up window just before a break starts.
     */
    PhasePreBreak = "prebreak",

    /**
     * PhaseShortBreak: a regular short break overlay is showing.
     */
    PhaseShortBreak = "shortbreak",

    /**
     * PhaseLongBreak: an occasional longer break overlay is showing.
     */
    PhaseLongBreak = "longbreak",

    /**
     * PhaseIdle: the user has been inactive past the idle threshold; the focus
     * timer is held and will reset when activity resumes.
     * 
     * Note: there is no PhasePaused constant. Pause() freezes the countdown by
     * setting the live boolean e.paused without changing the phase, so the
     * phase value during a user-pause is whatever it was when Pause was called
     * (typically PhaseFocusing). The frontend reads the `paused` boolean in
     * the emitted State, not the phase string, to detect pause.
     */
    PhaseIdle = "idle",
};

/**
 * State is the snapshot emitted to the frontend on every tick and phase change.
 * Durations are expressed in whole seconds for easy formatting in the UI.
 */
export interface State {
    "phase": Phase;
    "remainingSec": number;
    "totalSec": number;
    "breaksUntilLong": number;
    "shortBreakCount": number;
    "idle": boolean;
    "paused": boolean;
}
