// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Phase is the high-level state the engine is currently in. It is emitted to
 * the frontend as a string so the UI can switch views without parsing numbers.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PhaseFocusing: a work period is counting down toward the next break.
     */
    PhaseFocusing = "focusing",

    /**
     * PhasePreBreak: the heads-up window just before a break starts.
     */
    PhasePreBreak = "prebreak",

    /**
     * PhaseShortBreak: a regular short break overlay is showing.
     */
    PhaseShortBreak = "shortbreak",

    /**
     * PhaseLongBreak: an occasional longer break overlay is showing.
     */
    PhaseLongBreak = "longbreak",

    /**
     * PhasePaused: the user paused the engine; the countdown is frozen.
     */
    PhasePaused = "paused",

    /**
     * PhaseIdle: the user has been inactive past the idle threshold; the focus
     * timer is held and will reset when activity resumes.
     */
    PhaseIdle = "idle",
};

/**
 * State is the snapshot emitted to the frontend on every tick and phase change.
 * Durations are expressed in whole seconds for easy formatting in the UI.
 */
export interface State {
    "phase": Phase;
    "remainingSec": number;
    "totalSec": number;
    "breaksUntilLong": number;
    "shortBreakCount": number;
    "idle": boolean;
    "paused": boolean;
}
