// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings 是全部用户可配置行为。
 * 
 * 时长按 UI 自然编辑的单位拆分（长时段用分钟，短休息用秒），
 * 由 break engine 统一转换为 time.Duration。
 */
export interface Settings {
    /**
     * FocusDurationMin 是一次专注周期的时长，之后会提醒休息。
     */
    "focusDurationMin": number;

    /**
     * ShortBreakDurationSec 是常规短休息的时长。
     */
    "shortBreakDurationSec": number;

    /**
     * LongBreakDurationMin 是偶尔的较长休息的时长。
     */
    "longBreakDurationMin": number;

    /**
     * LongBreakInterval 是触发长休息前需要完成的短休息次数。
     */
    "longBreakInterval": number;

    /**
     * PreBreakWarningSec 是休息开始前的提前提醒时长。
     */
    "preBreakWarningSec": number;

    /**
     * IdleThresholdMin：不活动超过此时长后，专注计时器被视为暂停，
     * 活动恢复时重置。
     */
    "idleThresholdMin": number;

    /**
     * EnableLongBreaks 切换偶尔的长休息循环。
     */
    "enableLongBreaks": boolean;

    /**
     * SoundEnabled 切换休息结束提示音和休息前提醒音。
     */
    "soundEnabled": boolean;

    /**
     * AutoStart 在应用启动后（完成引导后）自动开始专注计时。
     * 为 false 时用户从托盘手动启动。
     */
    "autoStart": boolean;

    /**
     * Onboarded 记录用户是否已完成首次设置。
     * 在其为 true 之前引擎不运行倒计时，应用打开到设置页面而非立即倒计时。
     */
    "onboarded": boolean;

    /**
     * Language 是 UI 语言，"zh-CN" 或 "en"（空 = 跟随系统）。
     */
    "language": string;

    /**
     * Theme 是 UI 配色方案："system"（跟随系统）、"light" 或 "dark"。
     */
    "theme": string;

    /**
     * 全局键盘快捷键（Wails 加速键语法，如 "Cmd+Shift+B"）。
     */
    "shortcutStartBreak": string;
    "shortcutSkipBreak": string;
    "shortcutPostponeBreak": string;
    "shortcutPreferences": string;
}
