// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BreakService 是前端通过 Wails 绑定调用的 Go 类型。
 * 它是 break engine 之上的薄封装：engine 拥有计时状态机，
 * 此服务仅转发用户操作和设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as breakengine$0 from "./internal/breakengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "./internal/stats/models.js";

/**
 * AckClose 由前端在收到 blink:close-request、确认弹窗已显示后立即调用，
 * 用来停掉 Go 端的兜底定时器。
 * 
 * 拆成"接管 + 决定"两步，是为了让兜底超时只衡量前端的响应能力，
 * 而不把用户对着弹窗思考的时间也算进去（详见 prefs_close.go）。
 */
export function AckClose(): $CancellablePromise<void> {
    return $Call.ByID(799088405);
}

/**
 * CompleteOnboarding 标记引导完成并首次启动引擎。
 * 在用户完成首次设置界面后调用一次。
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1404130892);
}

/**
 * GetDayStats 返回指定日期的统计。year 为完整年份，month 为 1-12，day 为 1-31。
 */
export function GetDayStats(year: number, month: number, day: number): $CancellablePromise<stats$0.DayStats> {
    return $Call.ByID(4019884167, year, month, day);
}

/**
 * GetMonthlyStats 返回指定年月每天的专注/休息统计。
 * year 为完整年份（如 2026），month 为 1-12。
 * 前端据此渲染日历热力图。返回的 map key 为日期号（1-31）。
 */
export function GetMonthlyStats(year: number, month: number): $CancellablePromise<{ [_ in `${number}`]?: stats$0.DayStats } | null> {
    return $Call.ByID(738930098, year, month);
}

/**
 * GetPendingNav 返回并清除待处理的目标 tab 名。
 * 由托盘菜单的"统计"项设置，前端在 ready 后调用一次以切换到对应标签页。
 * 返回空串表示无待处理导航。
 */
export function GetPendingNav(): $CancellablePromise<string> {
    return $Call.ByID(3788134886);
}

/**
 * GetSettings 返回当前设置。
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1540088907);
}

/**
 * GetState 返回引擎的当前快照供 UI 渲染。
 */
export function GetState(): $CancellablePromise<breakengine$0.State> {
    return $Call.ByID(3372297283);
}

/**
 * Pause 冻结倒计时。
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(418148724);
}

/**
 * PostponeBreak 取消当前/即将到来的休息并重新开始专注周期。
 */
export function PostponeBreak(): $CancellablePromise<void> {
    return $Call.ByID(2245288207);
}

/**
 * Reset 清除长休息计数器并重新开始专注周期。
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(702969893);
}

/**
 * ResolveClose 接收前端关闭确认弹窗的结果，决定设置窗口关闭后的去向。
 * 
 * action 取 config.CloseActionBackground（保留在后台运行）、
 * config.CloseActionQuit（完全退出）或 closeActionCancel（用户取消，
 * 窗口保持打开）。remember 为 true 时把这次选择写入设置，之后关闭窗口
 * 不再询问——用户可在"选项 → 关闭窗口时"改回每次询问。
 * 
 * 该流程目前只有 Windows 会触发（其它平台不安装关闭钩子，前端也就
 * 收不到 blink:close-request 事件），但方法本身是平台无关的。
 * 
 * 线程：本方法是 Wails 绑定调用，运行在主线程上。窗口 Hide 与 app.Quit
 * 内部都会 InvokeSync 回主线程，直接调用会死锁，因此实际动作必须甩到
 * goroutine 上执行（与 ShowWindow 同理）。
 */
export function ResolveClose(action: string, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(2304484110, action, remember);
}

/**
 * Resume 继续暂停的倒计时。
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(389386909);
}

/**
 * SaveSettings 持久化设置，应用到运行中的引擎并重新绑定全局快捷键。
 * 快捷键重绑在自己的 goroutine 上运行，因为绑定会调度到主线程，
 * 而此方法本身就在主线程上运行（它是 Wails 绑定调用）。
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1647017906, settings);
}

/**
 * ShowWindow 显示设置窗口。由前端在数据加载完成、界面渲染就绪后调用，
 * 避免窗口先白屏再显示内容。Show/Focus 在独立 goroutine 上执行，
 * 因为它们内部通过 InvokeSync 调度到主线程，而本绑定方法本身就在
 * 主线程执行，直接调用会死锁。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(797210007);
}

/**
 * SkipBreak 结束当前休息或休息前提醒。
 */
export function SkipBreak(): $CancellablePromise<void> {
    return $Call.ByID(1930743036);
}

/**
 * StartBreakNow 立即开始休息，跳过休息前提醒。
 */
export function StartBreakNow(): $CancellablePromise<void> {
    return $Call.ByID(2949039075);
}

/**
 * StartEngine 启动倒计时（手动停止或暂停后使用）。
 */
export function StartEngine(): $CancellablePromise<void> {
    return $Call.ByID(1005774672);
}

/**
 * StopEngine 完全停止倒计时。
 */
export function StopEngine(): $CancellablePromise<void> {
    return $Call.ByID(729946672);
}
