// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BreakService is the Go type whose methods the frontend calls through Wails
 * bindings. It is a thin facade over the break engine: the engine owns the
 * timing state machine, this service just forwards user actions and settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as breakengine$0 from "./internal/breakengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * CompleteOnboarding marks onboarding done and starts the engine for the first
 * focus cycle. Called once the user finishes the first-run setup screen.
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1404130892);
}

/**
 * GetSettings returns the current settings.
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1540088907);
}

/**
 * GetState returns a snapshot of the engine for the UI to render.
 */
export function GetState(): $CancellablePromise<breakengine$0.State> {
    return $Call.ByID(3372297283);
}

/**
 * Pause freezes the countdown.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(418148724);
}

/**
 * PostponeBreak cancels the current/upcoming break and restarts the focus period.
 */
export function PostponeBreak(): $CancellablePromise<void> {
    return $Call.ByID(2245288207);
}

/**
 * Reset clears the long-break counter and restarts the focus period.
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(702969893);
}

/**
 * Resume continues a paused countdown.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(389386909);
}

/**
 * SaveSettings persists the settings, applies them to the running engine and
 * re-binds the global shortcuts. The shortcut rebind runs on its own goroutine
 * because binding marshals to the main thread and this method itself runs on
 * the main thread (it is a Wails binding call).
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1647017906, settings);
}

/**
 * SkipBreak ends the current break or pre-break warning.
 */
export function SkipBreak(): $CancellablePromise<void> {
    return $Call.ByID(1930743036);
}

/**
 * StartBreakNow forces a break immediately, skipping the pre-break warning.
 */
export function StartBreakNow(): $CancellablePromise<void> {
    return $Call.ByID(2949039075);
}

/**
 * StartEngine starts the countdown (used after a manual stop or pause).
 */
export function StartEngine(): $CancellablePromise<void> {
    return $Call.ByID(1005774672);
}

/**
 * StopEngine halts the countdown entirely.
 */
export function StopEngine(): $CancellablePromise<void> {
    return $Call.ByID(729946672);
}
