// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BreakService 是前端通过 Wails 绑定调用的 Go 类型。
 * 它是 break engine 之上的薄封装：engine 拥有计时状态机，
 * 此服务仅转发用户操作和设置。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as breakengine$0 from "./internal/breakengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * CompleteOnboarding 标记引导完成并首次启动引擎。
 * 在用户完成首次设置界面后调用一次。
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1404130892);
}

/**
 * GetSettings 返回当前设置。
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(1540088907);
}

/**
 * GetState 返回引擎的当前快照供 UI 渲染。
 */
export function GetState(): $CancellablePromise<breakengine$0.State> {
    return $Call.ByID(3372297283);
}

/**
 * Pause 冻结倒计时。
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(418148724);
}

/**
 * PostponeBreak 取消当前/即将到来的休息并重新开始专注周期。
 */
export function PostponeBreak(): $CancellablePromise<void> {
    return $Call.ByID(2245288207);
}

/**
 * Reset 清除长休息计数器并重新开始专注周期。
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(702969893);
}

/**
 * Resume 继续暂停的倒计时。
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(389386909);
}

/**
 * SaveSettings 持久化设置，应用到运行中的引擎并重新绑定全局快捷键。
 * 快捷键重绑在自己的 goroutine 上运行，因为绑定会调度到主线程，
 * 而此方法本身就在主线程上运行（它是 Wails 绑定调用）。
 */
export function SaveSettings(settings: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1647017906, settings);
}

/**
 * ShowWindow 显示设置窗口。由前端在数据加载完成、界面渲染就绪后调用，
 * 避免窗口先白屏再显示内容。Show/Focus 在独立 goroutine 上执行，
 * 因为它们内部通过 InvokeSync 调度到主线程，而本绑定方法本身就在
 * 主线程执行，直接调用会死锁。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(797210007);
}

/**
 * SkipBreak 结束当前休息或休息前提醒。
 */
export function SkipBreak(): $CancellablePromise<void> {
    return $Call.ByID(1930743036);
}

/**
 * StartBreakNow 立即开始休息，跳过休息前提醒。
 */
export function StartBreakNow(): $CancellablePromise<void> {
    return $Call.ByID(2949039075);
}

/**
 * StartEngine 启动倒计时（手动停止或暂停后使用）。
 */
export function StartEngine(): $CancellablePromise<void> {
    return $Call.ByID(1005774672);
}

/**
 * StopEngine 完全停止倒计时。
 */
export function StopEngine(): $CancellablePromise<void> {
    return $Call.ByID(729946672);
}
